Repair a missing std:: library on ArchLinux when I build the project by following the README.md statements
src/gl/shader.h:34:93: error: ‘vector’ in namespace ‘std’ does not name a template type
     load(const std::string& _fragmentSrc, const std::string& _vertexSrc, const std::vector<std::string> &_defines, bool _verbose = false);